name: pull_request

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: run benchmark
    runs-on: ubuntu-latest

    steps:
      - uses: webiny/action-post-run@2.0.1
        with:
          run: sh -c "find . -mindepth 1 -delete"
      - uses: actions/checkout@v2
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.5
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          mirrors: |
            [{
              "id": "mirror", 
              "name": "mirror", 
              "url": "https://repo1.maven.org/maven2", 
              "mirrorOf": "central"
            },{
              "id": "maven-default-http-blocker", 
              "name": "Pseudo repository to mirror external repositories initially using HTTP.", 
              "url": "http://0.0.0.0/", 
              "mirrorOf": "external:dummy:*",
              "blocked": "true"
            }]

      - name: Cache Hadoop
        uses: actions/cache@v2
        with:
          path: nebula/data/hadoop-3.2.1
          key: ${{ runner.os }}-hadoop-${{ hashFiles('nebula/scripts/env.sh') }}

      - name: Cache ldbc snb datagen
        uses: actions/cache@v2
        with:
          path: nebula/data/ldbc_snb_datagen
          key: ${{ runner.os }}-ldbc-${{ hashFiles('nebula/scripts/env.sh') }}

      - name: Build driver
        run: |
          git clone --branch 0.3.3 https://github.com/ldbc/ldbc_snb_driver
          pushd ldbc_snb_driver
          mvn clean install -DskipTests
          popd
          ./scripts/build.sh

      - name: Install NebulaGraph
        run: |
          mkdir tmp
          pushd tmp
          git clone https://github.com/vesoft-inc/nebula-docker-compose.git
          pushd nebula-docker-compose/
          docker-compose up -d
          sleep 10
          docker-compose ps
          popd
          popd
      - name: Generate and load data into NebulaGraph
        run: |
          cd nebula
          ./scripts/load.sh
      - name: run LDBC bench
        run: |
          rm -rf ../test-data
          mv ../data/ldbc_snb_datagen/test_data ../test-data
          sed -i 's/endpoint=.*/endpoint=127.0.0.1:9669/g' interactive-benchmark.properties
          sed -i 's/spaceName=.*/spanceName=sf0_1/g' interactive-benchmark.properties
          sed -i 's/operation_count=.*/operation_count=1000/g' interactive-benchmark.properties
          sed -i 's/ldbc.snb.interactive.scale_factor=.*/ldbc.snb.interactive.scale_factor=0.1/g' interactive-benchmark.properties
          ./interactive-benchmark.sh
        working-directory: nebula/driver/
      - name: cleanup
        if: ${{ always() }}
        run: |
          pushd tmp
          pushd nebula-docker-compose
          docker-compose down -v
